//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jfe_application
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JFEEntities : DbContext
    {
        public JFEEntities()
            : base("name=JFEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<BrandType> BrandTypes { get; set; }
        public virtual DbSet<Classification> Classifications { get; set; }
        public virtual DbSet<Manager> Managers { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<SalesRep> SalesReps { get; set; }
        public virtual DbSet<SiteCall> SiteCalls { get; set; }
        public virtual DbSet<Store> Stores { get; set; }
    }
}
