//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace jfe_application
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteCall
    {
        public int Id { get; set; }
        public System.DateTime datetimeCall { get; set; }
        public int classificationID { get; set; }
        public int salesRepID { get; set; }
        public int storeID { get; set; }
        public Nullable<int> displayBrands { get; set; }
        public Nullable<int> coldBrands { get; set; }
        public Nullable<int> largestCases { get; set; }
        public Nullable<int> coverage { get; set; }
        public Nullable<int> display { get; set; }
        public Nullable<int> currentCases { get; set; }
        public Nullable<int> total750mlCold { get; set; }
        public Nullable<int> schematicFacings { get; set; }
        public Nullable<int> coldBox { get; set; }
        public Nullable<int> pod { get; set; }
        public Nullable<int> cbf { get; set; }
        public string notes { get; set; }
    
        public virtual SalesRep SalesReps { get; set; }
        public virtual Classification Classification { get; set; }
        public virtual Store Stores { get; set; }
        public virtual Brand Brand { get; set; }
        public virtual Brand Brand1 { get; set; }
    }
}
